# Generated by Django 4.2.7 on 2024-02-22 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_added", models.DateField()),
                ("purchase_price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("total_profit", models.FloatField(default=0)),
                ("balance", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("selling_price", models.FloatField()),
                ("quantity_sold", models.IntegerField()),
                ("sale_date", models.DateField()),
                ("profit", models.FloatField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse_app.product",
                    ),
                ),
            ],
        ),
    ]
