# Generated by Django 4.2.7 on 2024-02-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehouse_app",
            "0002_remove_product_balance_remove_product_total_profit_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="total_given",
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
