# Generated by Django 4.2.7 on 2024-02-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0003_remove_product_total_given_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="product",
            name="selling_price",
        ),
        migrations.AddField(
            model_name="sale",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="sale",
            name="store",
            field=models.CharField(max_length=255),
        ),
    ]
