# Generated by Django 5.0.2 on 2024-03-02 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0004_remove_product_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="remaining_due",
        ),
    ]
