# Generated by Django 5.0.2 on 2024-03-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0005_remove_sale_phone_number_remove_sale_remaining_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
