# Generated by Django 5.0.2 on 2024-03-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0007_sale_payment_type_sale_remaining_due"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
