# Generated by Django 5.0.2 on 2024-03-08 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0008_sale_is_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="is_paid",
        ),
    ]
