# Generated by Django 5.0.2 on 2024-03-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0009_remove_sale_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
