# Generated by Django 5.0.2 on 2024-03-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0010_sale_is_paid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
