# Generated by Django 5.0.2 on 2024-03-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0011_profit"),
    ]

    operations = [
        migrations.AddField(
            model_name="profit",
            name="description",
            field=models.TextField(default="null"),
        ),
        migrations.AlterField(
            model_name="profit",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
