# Generated by Django 5.0.2 on 2024-03-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0012_profit_description_alter_profit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profit",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="profit",
            name="description",
            field=models.TextField(default="null", max_length=255),
        ),
    ]
