# Generated by Django 5.0.2 on 2024-03-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0013_alter_profit_date_alter_profit_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profit",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
