# Generated by Django 5.0.2 on 2024-03-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0015_profit_editable_alter_profit_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profit",
            name="editable",
        ),
        migrations.AlterField(
            model_name="profit",
            name="amount",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
