# Generated by Django 5.0.2 on 2024-03-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0016_remove_profit_editable_alter_profit_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profit",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="profit",
            name="description",
            field=models.TextField(default="null"),
        ),
    ]
