# Generated by Django 5.0.2 on 2024-03-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0017_alter_profit_amount_alter_profit_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="profit",
            name="editable",
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
