# Generated by Django 5.0.2 on 2024-03-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0018_profit_editable"),
    ]

    operations = [
        migrations.AddField(
            model_name="profit",
            name="total_profit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
