# Generated by Django 5.0.2 on 2024-03-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0019_profit_total_profit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profit",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="sale",
            name="product",
            field=models.ForeignKey(
                max_length=255,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse_app.product",
            ),
        ),
    ]
