# Generated by Django 5.0.2 on 2024-03-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0020_alter_profit_amount_alter_sale_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profit",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
