# Generated by Django 5.0.3 on 2024-03-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0021_alter_profit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='date',
            field=models.DateField(),
        ),
    ]
