# Generated by Django 5.0.3 on 2024-03-13 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0022_alter_profit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
