# Generated by Django 5.0.2 on 2024-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0023_alter_profit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
