# Generated by Django 5.0.2 on 2024-03-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0024_alter_product_purchase_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
