# Generated by Django 5.0.2 on 2024-03-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0025_alter_product_purchase_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="nomi",
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_type",
            field=models.CharField(
                choices=[("Naxt", "Naxt"), ("Nasiya", "Nasiya ")],
                default="full",
                max_length=20,
            ),
        ),
    ]
