# Generated by Django 5.0.2 on 2024-03-17 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0027_rename_quantity_product_soni_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="store",
            new_name="dokon",
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="profit",
            new_name="foyda",
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="product",
            new_name="mahsulot",
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="remaining_due",
            new_name="qarz",
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="selling_price",
            new_name="sotiladigan_narxi",
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="quantity_sold",
            new_name="sotilgan_soni",
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="payment_type",
            new_name="tolash_usuli",
        ),
    ]
