# Generated by Django 5.0.2 on 2024-03-17 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehouse_app",
            "0028_rename_store_sale_dokon_rename_profit_sale_foyda_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="profit",
            old_name="description",
            new_name="kommentariya",
        ),
        migrations.RenameField(
            model_name="profit",
            old_name="amount",
            new_name="olinadigan_summa",
        ),
    ]
