# Generated by Django 4.2.7 on 2024-03-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0029_rename_description_profit_kommentariya_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="sale_date",
            new_name="sotilgan_sana",
        ),
        migrations.AlterField(
            model_name="sale",
            name="tolash_usuli",
            field=models.CharField(
                choices=[("Naqt", "Naqt"), ("Nasiya", "Nasiya ")],
                default="full",
                max_length=20,
            ),
        ),
    ]
