# Generated by Django 4.2.7 on 2024-03-18 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0031_rename_sotilgan_soni_sale_soni"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profit",
            old_name="date",
            new_name="sana",
        ),
    ]
