# Generated by Django 4.2.7 on 2024-03-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0032_rename_date_profit_sana"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="tolash_usuli",
            field=models.CharField(
                choices=[("Naqd", "Naqd"), ("Nasiya", "Nasiya ")],
                default="full",
                max_length=20,
            ),
        ),
    ]
