# Generated by Django 5.0.4 on 2024-04-12 09:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0033_alter_sale_tolash_usuli'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.sale')),
            ],
        ),
    ]
